### ISSUE TITLE
Crash when formatting littleFS

### ISSUE THREAD

**Issue by bjonnh** [rppicomidi/midi2piousbhub#1]
The device seem to crash when running format.

Just programmed it (Pico W) for pico (I got the BT servers and client working properly).

Typing format it hangs and after a moment it disconnects even from USB.

**Comment by bjonnh** [comment]
If I reboot the board after sometimes I can use `ls` and sometimes I can save
but it is pretty random. The boards are both brand new.

**Comment by bjonnh** [comment]
save seem to have saved things anyway. so the crash may happen after the writting

**Comment by rppicomidi** [comment]
@bjonnh I will try to make time to investigate soon.

**Comment by rppicomidi** [comment]
@bjonnh Finally found time to work on this. Sorry, I should have checked the simple things first. I forgot to push the latest version of my fork of `littlefs-lib` when I comitted this project. I just pushed it. Please run 
```
git submodule update --recursive
````
 on this project and try again. Let me know if that fixes it for you.

**Comment by bjonnh** [comment]
It does indeed solve it, thanks a lot.
